CREATE TABLE User (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	First VARCHAR(30) NOT NULL,
	Last VARCHAR(30) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Password VARCHAR(30) NOT NULL,
	Role VARCHAR(15) NOT NULL,
	AmbulanceSquadId INT NOT NULL
)ENGINE=innodb;

CREATE TABLE AmbulanceSquad (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
	Street VARCHAR(30) NOT NULL,
	City VARCHAR(25) NOT NULL,
	State VARCHAR(2) NOT NULL,
	Zip VARCHAR(5) NOT NULL,
	Phone VARCHAR(10) NOT NULL
)ENGINE=innodb;

CREATE TABLE Ambulance (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Make VARCHAR(30) NOT NULL,
	Model VARCHAR(30) NOT NULL,
	Color VARCHAR(25) NOT NULL,
	AmbulanceSquadId INT NOT NULL
)ENGINE=innodb;

CREATE TABLE WorkSheet(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AmbulanceSquadId INT NOT NULL
)ENGINE=innodb;

create table Compartment(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WorkSheetId INT NOT NULL
)ENGINE=innodb;

/* INSERT INTO User VALUES(null, 'Deep', 'Patel', 'deep7176@gmail.com', 'lolWhut123', 'EMT', 1);